#!/usr/bin/env python3
"""Install the prebuilt systemd user units shipped with this bridge."""

from __future__ import annotations

import argparse
import pathlib
import re
import shutil
import subprocess
import sys

UNIT_NAMES = (
    "opencode-serve.service",
    "opencode-bridge-telegram.service",
    "opencode-bridge.target",
)
DROPIN_DIRNAME = "bridge-release.conf"
TAG_PATTERN = re.compile(r"^v[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z.-]+)?$")


def _run(argv: list[str], *, capture: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(argv, check=True, text=True, capture_output=capture)


def read_version() -> str:
    bridge_dir = pathlib.Path(__file__).resolve().parent
    version = (bridge_dir / "VERSION").read_text(encoding="utf-8").strip()
    if not version:
        raise SystemExit("VERSION is empty")
    return version


def deployed_tag() -> str:
    """Derive the tag from the immutable release tree, which has no .git dir."""
    tag = f"v{read_version()}"
    if not TAG_PATTERN.fullmatch(tag):
        raise SystemExit("VERSION cannot be represented as a release tag")
    return tag


def dropin_text(tag: str, version: str) -> str:
    return (
        "# Generated by systemd.py. Do not edit; regenerate on the next deployment.\n"
        "# A drop-in must declare its section, otherwise systemd discards it.\n"
        "[Service]\n"
        f"Environment=BRIDGE_RELEASE_TAG={tag}\n"
        f"Environment=BRIDGE_VERSION={version}\n"
    )


def install(dropins: bool) -> int:
    bridge_dir = pathlib.Path(__file__).resolve().parent
    source_dir = bridge_dir / "deploy"
    destination_dir = pathlib.Path.home() / ".config" / "systemd" / "user"
    destination_dir.mkdir(parents=True, exist_ok=True)

    for name in UNIT_NAMES:
        source = source_dir / name
        if not source.is_file():
            raise SystemExit(f"ملف الوحدة مفقود: {source}")
        destination = destination_dir / name
        shutil.copy2(source, destination)
        print(f"تم نسخ الوحدة: {destination}")

    if dropins:
        version = read_version()
        tag = deployed_tag()
        for name in UNIT_NAMES:
            unit_dropin = destination_dir / f"{name}.d"
            unit_dropin.mkdir(parents=True, exist_ok=True)
            target = unit_dropin / DROPIN_DIRNAME
            temporary = target.with_suffix(".tmp")
            temporary.write_text(dropin_text(tag, version), encoding="utf-8")
            temporary.replace(target)
            print(f"تم ختم الوحدة {name} بالوسم {tag}")

    _run(["systemctl", "--user", "daemon-reload"])
    _run(["systemctl", "--user", "enable", "opencode-bridge.target"])
    print("تم تحديث systemd. لإعادة التشغيل: systemctl --user restart opencode-bridge.target")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--no-dropin", action="store_true", help="skip stamping units with the release tag")
    arguments = parser.parse_args(argv)
    return install(dropins=not arguments.no_dropin)


if __name__ == "__main__":
    sys.exit(main())
