#!/usr/bin/env python3
"""Install the prebuilt systemd user units shipped with this bridge.

This helper only copies unit files and reloads systemd. It never builds code,
installs Python packages, or changes the bridge environment file.

Every unit is stamped with the release tag it came from, so ``systemctl cat``
answers "which version is running" without a second lookup. The stamp is written
as a drop-in rather than by editing the shipped unit, so re-running this script
over a new release replaces the stamp instead of accumulating them.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import shutil
import subprocess
import sys

UNIT_NAMES = (
    "opencode-serve.service",
    "opencode-bridge-telegram.service",
    "opencode-bridge.target",
)
DROPIN_DIRNAME = "bridge-release.conf"
TAG_PATTERN = re.compile(r"^v[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z.-]+)?$")


def _run(argv: list[str], *, capture: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        argv,
        check=True,
        text=True,
        capture_output=capture,
    )


def read_version() -> str:
    bridge_dir = pathlib.Path(__file__).resolve().parent
    version = (bridge_dir / "VERSION").read_text(encoding="utf-8").strip()
    if not version:
        raise SystemExit("VERSION is empty")
    return version


def deployed_tag() -> str:
    """Prefer the tag of the running checkout, then the recorded identity."""
    bridge_dir = pathlib.Path(__file__).resolve().parent
    identity = bridge_dir / "runtime" / "deployment-identity"
    if identity.is_file():
        match = re.search(
            r'"tag"\s*:\s*"(v[^"]+)"',
            identity.read_text(encoding="utf-8"),
        )
        if match and TAG_PATTERN.fullmatch(match.group(1)):
            return match.group(1)
    head = _run(["git", "-C", str(bridge_dir), "rev-parse", "HEAD"], capture=True).stdout.strip()
    described = subprocess.run(
        ["git", "-C", str(bridge_dir), "describe", "--tags", "--exact-match", head],
        text=True,
        capture_output=True,
    )
    if described.returncode == 0 and TAG_PATTERN.fullmatch(described.stdout.strip()):
        return described.stdout.strip()
    return f"v{read_version()}"


def dropin_text(tag: str, version: str) -> str:
    return (
        "# Generated by systemd.py. Do not edit; regenerate on the next deployment.\n"
        "# A drop-in must declare its section, otherwise systemd discards it.\n"
        "[Service]\n"
        f"Environment=BRIDGE_RELEASE_TAG={tag}\n"
        f"Environment=BRIDGE_VERSION={version}\n"
    )


def install(dropins: bool) -> int:
    bridge_dir = pathlib.Path(__file__).resolve().parent
    source_dir = bridge_dir / "deploy"
    destination_dir = pathlib.Path.home() / ".config" / "systemd" / "user"
    destination_dir.mkdir(parents=True, exist_ok=True)

    for name in UNIT_NAMES:
        source = source_dir / name
        if not source.is_file():
            raise SystemExit(f"ملف الوحدة مفقود: {source}")
        destination = destination_dir / name
        shutil.copy2(source, destination)
        print(f"تم نسخ الوحدة: {destination}")

    if dropins:
        version = read_version()
        tag = deployed_tag()
        for name in UNIT_NAMES:
            unit_dropin = destination_dir / f"{name}.d"
            unit_dropin.mkdir(parents=True, exist_ok=True)
            target = unit_dropin / DROPIN_DIRNAME
            temporary = target.with_suffix(".tmp")
            temporary.write_text(dropin_text(tag, version), encoding="utf-8")
            temporary.replace(target)
            print(f"تم ختم الوحدة {name} بالوسم {tag}")

    _run(["systemctl", "--user", "daemon-reload"])
    _run(["systemctl", "--user", "enable", "opencode-bridge.target"])
    print("تم تحديث systemd. لإعادة التشغيل: systemctl --user restart opencode-bridge.target")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--no-dropin",
        action="store_true",
        help="skip stamping the units with the release tag",
    )
    arguments = parser.parse_args(argv)
    return install(dropins=not arguments.no_dropin)


if __name__ == "__main__":
    sys.exit(main())
